---
title: "NonParametric"
author: "Steve Zhang"
date: "May 27, 2017"
output: html_document
---

```{r}
multiTest = function(x, prob) {
    k = length(x)
    n = sum(x)
    Q = sum((x - n*prob)^2/(n*prob))
    cat("X-squared:", Q, "\n")
    cat("Degrees of freedom:", k - 1, "\n")
    cat("P-value:", pchisq(Q, df = (k - 1), lower.tail = FALSE))
}
multiTest(c(58, 64, 67), prob = c(1/3, 1/3, 1/3))
```
```{r}
lows = seq(0.0, 0.9, 0.1)
highs = seq(0.1, 1.0, 0.1)
nums = runif(20000)
groups = rep(NA, 10)
for (i in 1:10) {
    groups[i] = sum(nums > lows[i] & nums < highs[i])
}
chisq.test(groups, p=rep(0.1, 10))
```

```{r}
#schools = matrix(c(24, 24, 17, 27, 23, 14, 8, 19, 12, 10, 13, 9), nrow = 4)
contTest = function(cont, alpha=0.05) {
    rows = matrix(rep(rowSums(cont), ncol(cont)), nrow = nrow(cont))
    cols = matrix(rep(colSums(cont), nrow(cont)), ncol = ncol(cont), byrow = TRUE)
    expected = (rows*cols/sum(cont))
    Q = sum((cont - expected)^2/expected)
    cat("Q statistics =", Q, "\n")
    R = nrow(cont)
    C = ncol(cont)
    deg = (R - 1) * (C - 1)
    cat("Degrees of freedom:", deg, "\n")
    cat("Minimum needed to reject null hypothesis:", qchisq((1 - alpha), df = deg) ,"\n")
    cat("P value:", pchisq(Q, df = deg, lower.tail = FALSE),"\n")
}
#contTest(schools)
```

```{r}
simMat = matrix(0, nrow = 3, ncol = 3)
trials = 300
for (i in 1:trials) {
    rand = runif(1)
    if (rand < 0.15) {
        simMat[1, 1] = simMat[1, 1] + 1
    } else if (rand < 0.30) {
        simMat[2, 1] = simMat[2, 1] + 1
    } else if (rand < 0.50) {
        simMat[3, 1] = simMat[3, 1] + 1
    } else if (rand < 0.59) {
        simMat[1, 2] = simMat[1, 2] + 1
    } else if (rand < 0.68) {
        simMat[2, 2] = simMat[2, 2] + 1
    } else if (rand < 0.80) {
        simMat[3, 2] = simMat[3, 2] + 1
    } else if (rand < 0.86) {
        simMat[1, 3] = simMat[1, 3] + 1
    } else if (rand < 0.92) {
        simMat[2, 3] = simMat[2, 3] + 1
    } else {
        simMat[3, 3] = simMat[3, 3] + 1
    }
}
contTest(simMat)
```
```{r}
hT = function(t) {
    summation = 0.0
    for (i in 1:10) {
        summation = summation + (-1)^(i - 1)*exp(-2*i^2*t^2)
    }
    return(1 - 2*summation)
}
tS = seq(0.30, 2.50, 0.10)
for (t in tS) {
    cat(t, ":", hT(t), "\n")
}
```
```{r}
trimMean = function(x, k){
    x = sort(x)
    n = length(x)
    return(mean(x[(k + 1):(n - k)]))
}
```

```{r}
signTest = function(x, med0, twoside = FALSE) {
    W = sum(x < med0)
    N = length(x)
    if (twoside == TRUE) {
        return(2*pbinom(W, N, prob = 0.5))
    } else {
        return(pbinom(W, N, prob = 0.5))
    }
}
hotdogs = c(186, 181, 176, 149, 184, 190, 158, 139, 175, 148, 152, 111, 141, 153, 190, 157, 131, 149, 135, 132)
signTest(hotdogs, 150, TRUE)
```

```{r}
rankTest = function(x, y) {
    m = length(x)
    n = length(y)
    expS = m*(m + n + 1) / 2
    sdS = sqrt(m * n *(m + n + 1)/12)
    combine = sort(c(x, y))
    sumRanks = sum(match(x, combine))
    Z = (sumRanks - expS)/sdS
    return(2*pnorm(Z, lower.tail = FALSE))
}
copper1 = c(2.183, 2.431, 2.55, 2.629, 2.641, 2.715, 2.805, 2.84)
copper2 = c(2.12, 2.153, 2.213, 2.24, 2.245, 2.266, 2.281, 2.336, 2.558, 2.587)
rankTest(copper1, copper2)
```

